### ISSUE TITLE
Unable to connect through ethernet

### ISSUE THREAD

**Issue by numo68** [OpenWave-GW/OpenWave-2KE#1]
Hi,

trying to connect to MSO-2204EA through LAN on windows 10 fails.

Checking with wireshark shows the software exchanging some 12 packets with the scope, then the scope resets the connection. See attach, the .65 is the PC, the .44 is the scope.

```
> OpenWave-2KE.exe 192.168.130.44:3000
...
OpenWave-2KE V1.05

192.168.130.44:3000
read(), socket error: [Errno 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "<string>", line 526, in <module>
  File "C:\OpenWave-2KE\OpenWave-2KE V1.05\build\OpenWave-2KE_myspec\out00-PYZ.pyz\dso2ke", line 88, in __init__
  File "C:\OpenWave-2KE\OpenWave-2KE V1.05\build\OpenWave-2KE_myspec\out00-PYZ.pyz\dso2ke", line 125, in connect
IndexError: list index out of range
```
[mso2204ea.zip](https://github.com/OpenWave-GW/OpenWave-2KE/files/4560767/mso2204ea.zip)

**Comment by numo68** [comment]
Not sure what happened but it works now. I can only say that I updated Win 10 in the meantime...
